name: Insider QA Automation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          sudo apt-get install -y google-chrome-stable || true
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin
          chmod +x /usr/local/bin/chromedriver
      - name: Run Tests
        run: |
          xvfb-run pytest --maxfail=1 --disable-warnings
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: error-screenshots
          path: utils/screenshots/error_screenshots/
